export const data = [
  {
    id: '1',
    question: "What is the capital city of Australia?",
    option1: "Sydney",
    option2: "Melbourne",
    option3: "Canberra",
    option4: "Brisbane",
    ans: 3,
  },
  {
    id: '2',
    question: "In which year did the Titanic sink?",
    option1: "1910",
    option2: "1912",
    option3: "1915",
    option4: "1920",
    ans: 2,
  },
  {
    id: '3',
    question: "Who wrote the play Romeo and Juliet?",
    option1: "William Wordsworth",
    option2: "William Shakespeare",
    option3: "Jane Austen",
    option4: "Charles Dickens",
    ans: 2,
  },
  {
    id: '4',
    question: "Which planet is known as the Red Planet?",
    option1: "Venus",
    option2: "Mars",
    option3: "Jupiter",
    option4: "Saturn",
    ans: 2,
  },
  {
    id: '5',
    question: "What is the largest ocean on Earth?",
    option1: "Atlantic Ocean",
    option2: "Indian Ocean",
    option3: "Pacific Ocean",
    option4: "Arctic Ocean",
    ans: 3,
  },
  {
    id: '6',
    question: "Who is known as the Father of Computer Science?",
    option1: 'Alan Turing',
    option2: 'Bill Gates',
    option3: 'Steve Jobs',
    option4: 'Mark Zuckerberg',
    ans: 1,
  },
  {
    id: '7',
    question: "What is the currency of Japan?",
    option1: 'Won',
    option2: 'Yen',
    option3: 'Ringgit',
    option4: 'Baht',
    ans: 2,
  },
  {
    id: '8',
    question: "Who painted the Mona Lisa?",
    option1: 'Vincent van Gogh',
    option2: 'Leonardo da Vinci',
    option3: 'Pablo Picasso',
    option4: 'Claude Monet',
    ans: 2,
  },
  {
    id: '9',
    question: "In which year did the Berlin Wall fall, leading to the reunification of Germany?",
    option1: '1985',
    option2: '1989',
    option3: '1991',
    option4: '1995',
    ans: 2,
  },
  {
    id: '10',
    question: " What is the largest mammal in the world?",
    option1: 'Elephant',
    option2: 'Gorilla',
    option3: 'Giraffe',
    option4: 'Blue Whale',
    ans: 4,
  },

];